--- 
elasticsearch: 
  command: "elasticsearch -Des.network.host=0.0.0.0"
  image: "elasticsearch:latest"
  ports: 
    - "9200:9200"
    - "9300:9300"
spring-boot:
  build: https://github.com/jacobben85/spring-boot-jboss.git
  environment:
    config.eshost: 192.168.56.102
    spring.datasource.url: jdbc:postgresql://192.168.56.102:5432/docker
  ports:
    - "8080:8080"
  links:
    - db
dockerui:
  image: "abh1nav/dockerui"
  privileged: true
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  ports:
   - "80:9000"
db:
  image: postgres
  environment:
    POSTGRES_DB: docker
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker
  ports:
   - "5432:5432"