--- 
elasticsearch: 
  command: "elasticsearch -Des.network.host=0.0.0.0"
  image: "elasticsearch:2.4.1"
  ports: 
    - "9200:9200"
    - "9300:9300"
spring-boot: 
  build: ./springboot
  environment:
    config.eshost: 192.168.56.102
  ports: 
    - "8080:8080"
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker