--- 
elasticsearch: 
  command: "elasticsearch -Des.network.host=0.0.0.0"
  image: "elasticsearch:latest"
  ports: 
    - "9200:9200"
    - "9300:9300"
#spring-boot: 
#  build: ./springboot
#  ports: 
#    - "8080:8080"
#mysqldb: 
#  container_name: db
#  environment: 
#    MYSQL_DATABASE: sample
#    MYSQL_PASSWORD: mysql
#    MYSQL_ROOT_PASSWORD: supersecret
#    MYSQL_USER: mysql
#  image: "mysql:latest"
#mywildfly: 
#  environment: 
#    - "MYSQL_URI=db:3306"
#  image: arungupta/wildfly-mysql-javaee7
#  ports: 
#    - "8080:8080"
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker
    
app:
  image: tutum/hello-world
  ports:
    - "8080:80"